### PR TITLE
Ib 31 migrate project to challenge

### PR DESCRIPTION
**Pull request by masterT**

### CODE REVIEW

**Comment by Corb3nik** [comment]
T'as tu checké mes commits? Mon affaire marche même pas messemble.

**Comment by masterT** [comment]
It's only to see the changes.

**Comment by masterT** [comment]
- use absolute path for api *.js
- challenge belongs_to ctf
- fix router.js

**Comment by masterT** [comment]
- use absolute path for api *.js
- challenge belongs_to ctf
- fix router.js
- separate rails server from Procfile.dev

**Pull request merged**
