### PR TITLE
Spider view UI #20

### PR DESCRIPTION
**Pull request by Corb3nik**
Adds the spider view UI.

Obviously there aren't any loading/progress bars yet, so you won't be able to tell if the scanning is in progress, but it should work.

### CODE REVIEW

**Comment by masterT** [comment]
We really need to rework the UI, it's not practical.
screen shot 2017-06-23 at 09 58 31

**Comment by Corb3nik** [comment]
@masterT Yes I agree. As you've mentionned before, we could probably set the sections horizontally instead of vertically. I'll open a new issue for this.

**Comment by Corb3nik** [comment]
Or should I just rework it in this branch?

**Comment by masterT** [comment]
As you wish! ;)

**Pull request merged**
